// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARzMaCJUeKyQqAlvIPvk7Av2HBuncv5gc',
    appId: '1:154587843348:web:93497886a8479180f25001',
    messagingSenderId: '154587843348',
    projectId: 'ai-class-c0f38',
    authDomain: 'ai-class-c0f38.firebaseapp.com',
    storageBucket: 'ai-class-c0f38.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDasl8orD1vLjAoKFG20MI7x1tBt43tz3U',
    appId: '1:154587843348:android:f06c3dddc07ee07df25001',
    messagingSenderId: '154587843348',
    projectId: 'ai-class-c0f38',
    storageBucket: 'ai-class-c0f38.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIJlWUzDL4O6E-DWpFW5NjjFHJPyM2gcQ',
    appId: '1:154587843348:ios:e52d6e0f8d3e518cf25001',
    messagingSenderId: '154587843348',
    projectId: 'ai-class-c0f38',
    storageBucket: 'ai-class-c0f38.firebasestorage.app',
    androidClientId: '154587843348-u7q7q50ca39ocg8sal03ag55936qdh0p.apps.googleusercontent.com',
    iosClientId: '154587843348-c4evlb0bodph6897cuvbpebetf4816a3.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIJlWUzDL4O6E-DWpFW5NjjFHJPyM2gcQ',
    appId: '1:154587843348:ios:e52d6e0f8d3e518cf25001',
    messagingSenderId: '154587843348',
    projectId: 'ai-class-c0f38',
    storageBucket: 'ai-class-c0f38.firebasestorage.app',
    androidClientId: '154587843348-u7q7q50ca39ocg8sal03ag55936qdh0p.apps.googleusercontent.com',
    iosClientId: '154587843348-c4evlb0bodph6897cuvbpebetf4816a3.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARzMaCJUeKyQqAlvIPvk7Av2HBuncv5gc',
    appId: '1:154587843348:web:fd8953973216acb0f25001',
    messagingSenderId: '154587843348',
    projectId: 'ai-class-c0f38',
    authDomain: 'ai-class-c0f38.firebaseapp.com',
    storageBucket: 'ai-class-c0f38.firebasestorage.app',
  );

}